apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: javawebapp-ENVIRONMENT-BUILD_NUMBER
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: javawebapp
        version: "BUILD_NUMBER"
    spec:
      containers:
      - name: javawebapp-ENVIRONMENT-BUILD_NUMBER
        image: IMAGE
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: javaweabppingressrule
  namespace: test-ns
spec:
  ingressClassName: nginx
  rules:
  - host: javawebapp.eccentricweb.in
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: javawebappsvc
            port:
              number: 80       
