---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: javawebapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: javawebapp
    spec:
      containers:
      - image: vkpatilhsit/azure-java-web-app:32
        name: javawebapp
        ports:
        - name: javawebapp
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: javawebapp
  name: javawebapp
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: javawebapp
