apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
  namespace: mynamespace
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: vkpatilhsit/java-web-application:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /java-web-app
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /java-web-app
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
 name: javawebappsvc
 namespace: mynamespace
spec:
  type: Nodeport
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080
