name: Java CI with Maven
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build, tag docker image to dockerhub
      run: |
        docker build -t vkpatilhsit/githubactionrepo:latest .
    - name: Scan image
      uses: Azure/container-scan@v0
      with:
        image-name: vkpatilhsit/githubactionrepo:latest
        severity-threshold: CRITICAL
        run-quality-checks: true
    - name: push docker image to docker hub
      run: |
        docker push vkpatilhsit/githubactionrepo:latest 
